### ISSUE TITLE
NGINX recipe does not configure basepath

### ISSUE THREAD

**Issue by mbassett** [kemra102/yumserver-cookbook#1]
The actual yum mirroring works well I'm getting the files downloaded, but the nginx recipe only installs nginx and does nothing else...

Also it seems you are hardcoding the servername to 'servername' in the _nginx.rb

should read    variables(
    nginx_servername: node['yumserver']['nginx']['servername']
  )

this is the entirety of the nginx config that your recipe generates

server {
  listen      80;
  server_name servername;

  access_log  /var/log/nginx/servername.access.log main;
  location / {
    root  html;
    index index.html;
  }
}

**Comment by mbassett** [comment]
Looking at the source this may be a issue with the package in chef supermarket and fixed locally, trying from trunk

**Comment by kemra102** [comment]
Good spot, do you want to submit the fixes yourself? If not I'm happy to get it done.

**Comment by mbassett** [comment]
created the PR just now
