### ISSUE TITLE
timeout creating large repos

### ISSUE THREAD

**Issue by caboteria** [kemra102/yumserver-cookbook#10]
Looks like the default timeout for the rsync operation is 600s which isn't long enough to rsync a big repo (like epel) for the first time.  shell_out() does allow a timeout parameter, but that isn't currently set by this cookbook.

What do you think is the best way to set this timeout?  We could add another property to rsync_mirror.rb which would allow the timeout to be set in yumserver_rsync_mirror.  Does this seem like a useful enhancement?  If so I could look at adding a PR.

**Comment by caboteria** [comment]
BTW, I found a commit that looks like it addresses this problem in one of the forks: https://github.com/mwiczynski-cartera/yumserver-cookbook/commit/6d4a2c6daad13091f136b37dca978a97241b52a6

**Comment by kemra102** [comment]
I had actually intended to do something like this at some point as it would also satisfy #8 with a greater degree of flexibility.

I'll see about cherry picking in the changes later and adding some documentation.

**Comment by caboteria** [comment]
Cool, thanks!
