### ISSUE TITLE
createrepo runs at every chef_client run

### ISSUE THREAD

**Issue by mbassett** [kemra102/yumserver-cookbook#3]
This isn't a problem exactly, except it takes a very long time for the chef_client to finish, and chef_client runs every ~ 30 minutes so it's probably not necessary to createrepo every time.

Haven't figured out a good way to accomplish this though.. maybe creating a last_run timestamp per site repo and checking that it is x minutes since then?

Thoughts?

**Comment by kemra102** [comment]
One option is to update the `interval` in `client.rb` but that's not ideal.

Timestamp of some description might be OK, perhaps something like this:

```ruby
ruby_block 'reposync' do
  block do
    system "reposync -r #{repo_name} -p #{full_path}"
  end
  only_if "[ find #{full_path} -mmin +360 ]"
end
```
That *should* only run createrepo every 6 hours assuming there's been a change, though I haven't tested it and there are all kinds of other possible issues with it. That would need significant testing.

I really don't know the answer, I'll run it passed some people as it's definitely a "problem". In the mean time I'm happy to take more suggestions.

**Comment by kemra102** [comment]
After doing some testing today and setting up a number of repos I don't think this is necessarily as big an issue as we may have imagined.

It seems that reposync does not re-download packages each time so after the first run it should only get changes. Now createrepo DOES run every time no matter what but that's relatively painless.

Additionally I committed the code to allow you to do rsync mirrors, which are much quicker in my experience and keep the delta synced quite well. The major projects like CentOS, Fedora (including EPEL) & IUS all provide rsync as an option for their repos.

I have considered replacing the reposync/createrepo resource with something pure ruby based, but that's just an early idea at this point.

**Comment by kemra102** [comment]
So in the RHEL7 man pages that option reads as:

```
-C --checkts
              Don't  generate  repo  metadata, if their timestamps are newer than its rpms.  This option decreases the processing
              time drastically again, if you happen to run it on an unmodified repo, but it is (currently) mutual exclusive  with
              the  --split  option. NOTE: This command will not notice when packages have been removed from repo. Use --update to
              handle that.
```

So perhaps the **--update** option would be much better:

```
--update
              If metadata already exists in the outputdir and an rpm is unchanged (based on file size and mtime) since the  meta‐
              data  was  generated,  reuse  the existing metadata rather than recalculating it. In the case of a large repository
              with only a few new or modified rpms this can significantly reduce I/O and processing time.
```

I haven't had time to test either situation but **-C** sounds insufficient given that it doesn't notice removed packages (though admittedly that should be a rare occurrence).

**Comment by jshupe** [comment]
--update looks good to me. I'll set that in my testing env.

**Comment by kemra102** [comment]
As there's such a difference I'm happy to use **-C**, really the only time a package should disappear from a repo is when a newer version replaces it so createrepo will refresh the metadata anyway. If you fancy submitting a pull request for this one please do so.

**Comment by kemra102** [comment]
As the `rsync_mirror` resource is now available and the **-C** option is now implemented on **createrepo** and released to the Supermarket I'm going to close this.
